### ISSUE TITLE
Firebase support

### ISSUE THREAD

**Issue by Elter71** [Rotorsoft/eventually-monorepo#42]
Hi, do you have an example of how to use eventually with firebase (firestore/google pub/sub tip.)?

**Comment by Rotorsoft** [comment]
Hi,

You can write a firestore adapter similar to this one https://github.com/Rotorsoft/eventually-monorepo/blob/master/libs/eventually-pg/src/PostgresStore.ts, it's just implementing the Store interface

You can also use GCP pub/sub to push events to REST endpoints, but if you need better guarantees than pub/sub queues,  you can move events from pub/sub to persisted streams... this is how the broker connects producers and consumers

Hope it helps!

**Comment by TomKaltz** [comment]
> ...you can move events from pub/sub to persisted streams...
@Rotorsoft Can you elaborate on this?

I am currently implementing stores adapters on top of Firebase Firestore and it's working pretty well so far but I'm curious how I would effectively connect services together in a serverless environment.  I see there is a broker service but it seems to work by polling streams.  Do you not recommend services **push** events to pub/sub and subsequently be pushed to a subscribing service?

**Comment by Rotorsoft** [comment]
Hey Tom, you are right about the broker service. It's a work in progress though. Since this framework is mainly focused on Event Sourcing, the broker was designed to pull from producer channels (primarily event streams, to keep message ordering and "at-least-once" guarantees), and push to consumer channels (especially HTTP Post event handlers - policies, projectors). You can try alternatives like pub/sub, just watch for ordering and message retention if you ever need to replay streams.

The broker provides basic event filtering (using regex), batching, retry mechanisms, and circuit breakers... but it's missing important stuff like joining streams (to order events by creation time) and other common integration patterns... again, a WIP that needs more helping hands ;-) 

I've been focusing lately on the ESML project, trying to generate ES models out of ChatGPT, and eventually some automated "eventually service" scaffolding out of ESML... as time permits. At some point in the future, I would like to have a simpler broker that discovers services and connects them automatically by interpreting the OpenAPI specs (with minimal configuration)... ESML contexts are a good way to visualize this.

Hope this helps.

Best

**Comment by TomKaltz** [comment]
I noticed while testing on firebase functions v2 (cloud run) that the in memory broker poll scheduler is not awaited anywhere.  Due to this, it will get frozen by cloud run at the end of the command http request cycle usually before event processing has completed.  This will cause pending actions in the scheduler to not complete until another http request comes in.  This can also cause the stream lease to expire and events to be needlessly reprocessed.

To support running eventually services on firebase functions, should broker.poll() be changed to return a promise which resolves after the scheduler has finished processing events?  Obviously poll() would also need to be triggered out of band of the current https request.  Perhaps by triggering an http "poll" endpoint using cloud tasks or pub/sub push that will complete the poll cycle within that http request.

**Comment by TomKaltz** [comment]
@Rotorsoft feel free to email me tomkaltz at gmail
