### ISSUE TITLE
bind() does not require stream name when returning a command

### ISSUE THREAD

**Issue by TomKaltz** [Rotorsoft/eventually-monorepo#55]
When returning a command from an event handler, ```bind()``` does not catch if you have omitted a target stream name.  It is caught at runtime [here](https://github.com/Rotorsoft/eventually-monorepo/blob/6572a1d4d51ca89041751f72a82dfb5cbfb2f84e/libs/eventually/src/handlers/command.ts#L32) but should be caught at compile time.

Perhaps a message specific ```bind()``` should be injected into the handler so the user can do something like the following...

```ts
on: {
  AnEvent: async (event, state, bind) => {
    // if returning a command the resulting message will have the appropriate CommandTarget information automatically added    
    return bind('ACommand', {
      somedata: 'blah blah blah'
    })
  }
}
```

**Comment by Rotorsoft** [comment]
The process you are describing happens here

https://github.com/Rotorsoft/eventually-monorepo/blob/6572a1d4d51ca89041751f72a82dfb5cbfb2f84e/libs/eventually/src/handlers/event.ts#L51

but the stream name is part of the business logic and cannot be automatically added 

Another solution is to provide a more specific “bindCommand” utility with required target instead of the generic message bind, but it will be always up to the developer to use the right binder and properly unit test the flow.
